#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'commander'
require 'tsm'
require 'io/console'

class MyApplication

  include Commander::Methods

  def run
    puts "Running"
    program :name, 'tsm'
    program :version, '0.0.1'
    program :description, 'Run TSM server commands'

    command :query do |c|
      c.syntax = 'tsm query [options]'
      c.summary = 'TSM Query'
      c.description = 'Run a TSM query command to the background process started.'
      c.example 'Run Query:', 'tsm query q db'
      c.option '--detail', 'Add format=detail to the output'
      c.action do |args, options|
        # Do something or c.when_called Run::Commands::Query
        server = Tsm::Server.new
        loop do
          print "outfile|size|reinit|quit|save <f>|cmd>: "
          cmd = STDIN.gets.chomp
          case cmd
          when /^save \w*/
            file = cmd.split(" ",2).last
            puts "Saving to #{file}"
            server.save(file)
          when "size"
            puts server.output.size
          when "outfile"
            puts server.output.path
          when "quit"
            server.quit
            break
          when "reinit"
            server.reinit
          else
            res = server.exec(cmd)
            puts res.data
          end
        end
      end
    end

    run!
  end
end

MyApplication.new.run 
